/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.ClsFactura;
import java.awt.Color;

/**
 *
 * @author monta
 */
public class frmcuentasporcobrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prueba
     */
    public frmcuentasporcobrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        cmbfacturas = new javax.swing.JComboBox<>();
        txtimporte = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtransacc = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 75, 159));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_bank_building_50px_2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuentas por cobrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 120));

        txtbuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.setText("Buscar fechas de Pago");
        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarMousePressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 30));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_search_30px.png"))); // NOI18N
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 50, 30));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        cmbfacturas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(cmbfacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 40));

        txtimporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtimporte.setForeground(new java.awt.Color(204, 204, 204));
        txtimporte.setText("0000000");
        txtimporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtimporteMousePressed(evt);
            }
        });
        txtimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteKeyTyped(evt);
            }
        });
        getContentPane().add(txtimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 40));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 40));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 40));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setText("Nª de Faturas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setText("Importe");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        btnagregar.setBackground(new java.awt.Color(0, 112, 224));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("AGREGAR");
        btnagregar.setBorder(null);
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 90, 40));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 10, 430));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1180, 10));

        jScrollPane1.setBorder(null);

        tbtransacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbtransacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Importe", "Fecha Vencimiento", "Fecha de Pago", "Nº Factura"
            }
        ));
        tbtransacc.setGridColor(new java.awt.Color(255, 255, 255));
        tbtransacc.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbtransacc.setRowHeight(25);
        tbtransacc.setSelectionBackground(new java.awt.Color(0, 112, 224));
        jScrollPane1.setViewportView(tbtransacc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 490, 260));

        btnactualizar.setBackground(new java.awt.Color(0, 112, 224));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_update_30px.png"))); // NOI18N
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 290, 50, 40));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setText("Datos Guardados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, 40));

        btngenerar.setBackground(new java.awt.Color(0, 112, 224));
        btngenerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btngenerar.setForeground(new java.awt.Color(255, 255, 255));
        btngenerar.setText("GENERAR REPORTE");
        btngenerar.setBorder(null);
        getContentPane().add(btngenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 170, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de Vencimineto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 30));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de Pago");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMousePressed

        if(this.txtbuscar.getText().equals("Buscar fechas de Pago")){
            this.txtbuscar.setText("");
            this.txtbuscar.setForeground(Color.black);
        }
        if(String.valueOf(this.txtimporte.getText()).isEmpty()){
            this.txtimporte.setText("0000000");
            this.txtimporte.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtbuscarMousePressed

    private void txtimporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtimporteMousePressed
        if(this.txtimporte.getText().equals("0000000")){
            this.txtimporte.setText("");
            this.txtimporte.setForeground(Color.black);
        }

        if(String.valueOf(this.txtbuscar.getText()).isEmpty()){
            this.txtbuscar.setText("Buscar fechas de Pago");
            this.txtbuscar.setForeground(new Color(204,204,204));
        }

    }//GEN-LAST:event_txtimporteMousePressed

    private void txtimporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')   evt.consume();
    }//GEN-LAST:event_txtimporteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btngenerar;
    public javax.swing.JComboBox<ClsFactura> cmbfacturas;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tbtransacc;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtimporte;
    // End of variables declaration//GEN-END:variables
}
