/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author monta
 */
public class frmCuentasBancarias extends javax.swing.JPanel {

    /**
     * Creates new form frmCuentasBancarias
     */
    public frmCuentasBancarias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcuenta = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 75, 159));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_account_50px_1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuentas Bancarias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1192, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 10, 430));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1180, 10));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setText("Nombre del Banco");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtnombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(204, 204, 204));
        txtnombre.setText("Ingrese Nombre del Banco");
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreMousePressed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 320, 40));

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setText("Numero de Cuenta");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        txtnumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtnumero.setForeground(new java.awt.Color(204, 204, 204));
        txtnumero.setText("Ingrese Numero de Cuenta");
        txtnumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnumeroMousePressed(evt);
            }
        });
        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 200, 40));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setText("Saldo");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtsaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtsaldo.setForeground(new java.awt.Color(204, 204, 204));
        txtsaldo.setText("Ingrese Saldo");
        txtsaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtsaldoMousePressed(evt);
            }
        });
        txtsaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsaldoKeyTyped(evt);
            }
        });
        add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 40));

        btnIngresar.setBackground(new java.awt.Color(0, 112, 224));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-guardar-94.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-40.png"))); // NOI18N
        btnUpdate.setBorder(null);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-40.png"))); // NOI18N
        btnEliminar.setBorder(null);
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-broom-with-a-lot-of-dust-40.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar.gif"))); // NOI18N
        btnactualizar.setBorder(null);
        add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jScrollPane1.setBorder(null);

        tbcuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbcuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Banco", "Numero de Cuenta", "Saldo"
            }
        ));
        tbcuenta.setGridColor(new java.awt.Color(255, 255, 255));
        tbcuenta.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbcuenta.setRowHeight(25);
        tbcuenta.setSelectionBackground(new java.awt.Color(0, 112, 224));
        jScrollPane1.setViewportView(tbcuenta);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 250));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel13.setText("Datos Guardados");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_search_30px.png"))); // NOI18N
        add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscar.setText("Buscar  Banco");
        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarMousePressed(evt);
            }
        });
        add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, 30));
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMousePressed
        if(this.txtnombre.getText().equals("Ingrese Nombre del Banco")){
            this.txtnombre.setText("");
            this.txtnombre.setForeground(Color.black);
        }

        if(String.valueOf(this.txtbuscar.getText()).isEmpty()){
            this.txtbuscar.setText("Buscar  Banco");
            this.txtbuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtnumero.getText()).isEmpty()){
            this.txtnumero.setText("Ingrese Numero de Cuenta");
            this.txtnumero.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtsaldo.getText()).isEmpty()){
            this.txtsaldo.setText("Ingrese Saldo");
            this.txtsaldo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtnombreMousePressed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped

    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnumeroMousePressed
        if(this.txtnumero.getText().equals("Ingrese Numero de Cuenta")){
            this.txtnumero.setText("");
            this.txtnumero.setForeground(Color.black);
        }

        if(String.valueOf(this.txtbuscar.getText()).isEmpty()){
            this.txtbuscar.setText("Buscar  Banco");
            this.txtbuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtnombre.getText()).isEmpty()){
            this.txtnombre.setText("Ingrese Nombre del Banco");
            this.txtnombre.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtsaldo.getText()).isEmpty()){
            this.txtsaldo.setText("Ingrese Saldo");
            this.txtsaldo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtnumeroMousePressed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')   evt.consume();
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtsaldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsaldoMousePressed
        if(this.txtsaldo.getText().equals("Ingrese Saldo")){
            this.txtsaldo.setText("");
            this.txtsaldo.setForeground(Color.black);
        }

        if(String.valueOf(this.txtbuscar.getText()).isEmpty()){
            this.txtbuscar.setText("Buscar  Banco");
            this.txtbuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtnombre.getText()).isEmpty()){
            this.txtnombre.setText("Ingrese Nombre del Banco");
            this.txtnombre.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtnumero.getText()).isEmpty()){
            this.txtnumero.setText("Ingrese Numero de Cuenta");
            this.txtnumero.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtsaldoMousePressed

    private void txtsaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsaldoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')   evt.consume();
    }//GEN-LAST:event_txtsaldoKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMousePressed

        if(this.txtbuscar.getText().equals("Buscar  Banco")){
            this.txtbuscar.setText("");
            this.txtbuscar.setForeground(Color.black);
        }
        if(String.valueOf(this.txtnombre.getText()).isEmpty()){
            this.txtnombre.setText("Ingrese Nombre del Banco");
            this.txtnombre.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtnumero.getText()).isEmpty()){
            this.txtnumero.setText("Ingrese Numero de Cuenta");
            this.txtnumero.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtsaldo.getText()).isEmpty()){
            this.txtsaldo.setText("Ingrese Saldo");
            this.txtsaldo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtbuscarMousePressed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tbcuenta;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnumero;
    public javax.swing.JTextField txtsaldo;
    // End of variables declaration//GEN-END:variables
}
