/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClsProveedor;
import java.awt.Color;

/**
 *
 * @author joel
 */
public class frmFacturas extends javax.swing.JPanel {

    /**
     * Creates new form frmFacturas
     */
    public frmFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbcliente = new javax.swing.JComboBox<>();
        txtimporte = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbfactura = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        btngenerar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtimporteclie = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbprovee = new javax.swing.JComboBox<>();
        txtnumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtimportepro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_estimate_50px.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 110));

        jLabel3.setBackground(new java.awt.Color(0, 75, 159));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("    Facturas");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_estimate_50px.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 110));

        cmbcliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbclienteActionPerformed(evt);
            }
        });
        add(cmbcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 40));

        txtimporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtimporte.setEnabled(false);
        txtimporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtimporteMousePressed(evt);
            }
        });
        txtimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteKeyTyped(evt);
            }
        });
        add(txtimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 160, 40));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 160, 40));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setText("importe");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setText("Importe Total");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 130, 30));

        btnagregar.setBackground(new java.awt.Color(0, 112, 224));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("AGREGAR");
        btnagregar.setBorder(null);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1180, 10));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Fecha");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 170, 30));

        jScrollPane1.setBorder(null);

        tbfactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbfactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Numero Factura", "Fecha", "Clientes", "Importe Cliente", "Proveedores", "Importe Proveedores", "Importe Total"
            }
        ));
        tbfactura.setGridColor(new java.awt.Color(255, 255, 255));
        tbfactura.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbfactura.setRowHeight(25);
        tbfactura.setSelectionBackground(new java.awt.Color(0, 112, 224));
        jScrollPane1.setViewportView(tbfactura);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 490, 260));

        btnactualizar.setBackground(new java.awt.Color(0, 112, 224));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_update_30px.png"))); // NOI18N
        btnactualizar.setBorder(null);
        add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 475, 50, 40));

        btngenerar.setBackground(new java.awt.Color(0, 112, 224));
        btngenerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btngenerar.setForeground(new java.awt.Color(255, 255, 255));
        btngenerar.setText("GENERAR REPORTE");
        btngenerar.setBorder(null);
        add(btngenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 170, 40));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setText("Datos Guardados");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 173, 130, 30));
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 20, 430));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setText("Numero de Factura");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 50));

        txtimporteclie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtimporteclie.setEnabled(false);
        txtimporteclie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtimporteclieMousePressed(evt);
            }
        });
        txtimporteclie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteclieKeyTyped(evt);
            }
        });
        add(txtimporteclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 80, 40));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel13.setText("Proveedor");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        cmbprovee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbprovee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbproveeActionPerformed(evt);
            }
        });
        add(cmbprovee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 40));

        txtnumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtnumero.setForeground(new java.awt.Color(204, 204, 204));
        txtnumero.setText("Ingrese numero de Factura");
        txtnumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnumeroMousePressed(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 260, 40));

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setText("Cliente");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtimportepro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtimportepro.setEnabled(false);
        txtimportepro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtimporteproMousePressed(evt);
            }
        });
        txtimportepro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteproKeyTyped(evt);
            }
        });
        add(txtimportepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 80, 40));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setText("importe");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbclienteActionPerformed

    private void txtimporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtimporteMousePressed
       
    }//GEN-LAST:event_txtimporteMousePressed

    private void txtimporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')   evt.consume();
    }//GEN-LAST:event_txtimporteKeyTyped

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void txtimporteclieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtimporteclieMousePressed
        

    }//GEN-LAST:event_txtimporteclieMousePressed

    private void txtimporteclieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteclieKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')   evt.consume();
    }//GEN-LAST:event_txtimporteclieKeyTyped

    private void cmbproveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbproveeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbproveeActionPerformed

    private void txtnumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnumeroMousePressed
         if(this.txtnumero.getText().equals("Ingrese numero de Factura")){
            this.txtnumero.setText("");
            this.txtnumero.setForeground(Color.black);
        }

        
    }//GEN-LAST:event_txtnumeroMousePressed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtimporteproMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtimporteproMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteproMousePressed

    private void txtimporteproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteproKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteproKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btngenerar;
    public javax.swing.JComboBox<Cliente> cmbcliente;
    public javax.swing.JComboBox<ClsProveedor> cmbprovee;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tbfactura;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtimporte;
    public javax.swing.JTextField txtimporteclie;
    public javax.swing.JTextField txtimportepro;
    public javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
