/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ctrl_Login;
import Modelo.ClsConsultaUsuario;
import Modelo.Usuario;
import java.awt.Color;

/**
 *
 * @author monta
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnIngresar = new javax.swing.JButton();
        jtxtClave = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 75, 159));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN DE ACCESO / SISTEMA CONTABLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSalir.setBackground(new java.awt.Color(0, 75, 159));
        jbtnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setText("SALIR");
        jbtnSalir.setBorder(null);
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 90, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/149071.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 140));

        jbtnIngresar.setBackground(new java.awt.Color(0, 75, 159));
        jbtnIngresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIngresar.setText("INGRESAR");
        jbtnIngresar.setBorder(null);
        jbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 189, 49));

        jtxtClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtClave.setForeground(new java.awt.Color(204, 204, 204));
        jtxtClave.setText("Ingrese contraseña");
        jtxtClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtClaveMousePressed(evt);
            }
        });
        jtxtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClaveActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 240, 34));

        jtxtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jtxtUsuario.setText("Ingrese usuario");
        jtxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtUsuarioMousePressed(evt);
            }
        });
        jPanel2.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, 35));

        jButton2.setBackground(new java.awt.Color(0, 75, 159));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_microsoft_admin_24px.png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 40));

        jButton1.setBackground(new java.awt.Color(0, 75, 159));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_client_management_24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 560, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarActionPerformed
        Usuario usuario = new Usuario();
        ClsConsultaUsuario consulta_usuario = new ClsConsultaUsuario();
        frmLogin frmlogin = new frmLogin();
        ctrl_Login ctrl = new ctrl_Login(frmlogin,usuario,consulta_usuario);
        if(ctrl.Log(jtxtUsuario.getText(),jtxtClave.getText())){
            dispose();
        }
    }//GEN-LAST:event_jbtnIngresarActionPerformed

    private void jtxtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClaveActionPerformed
         
    }//GEN-LAST:event_jtxtClaveActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUsuarioMousePressed
        if(this.jtxtUsuario.getText().equals("Ingrese usuario")){
            this.jtxtUsuario.setText("");
            this.jtxtUsuario.setForeground(Color.black);
        }

       
        if(String.valueOf(this.jtxtClave.getText()).isEmpty()){
            this.jtxtClave.setText("Ingrese contraseña");
            this.jtxtClave.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jtxtUsuarioMousePressed

    private void jtxtClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtClaveMousePressed
        if(this.jtxtClave.getText().equals("Ingrese contraseña")){
            this.jtxtClave.setText("");
            this.jtxtClave.setForeground(Color.black);
        }

        
        if(String.valueOf(this.jtxtUsuario.getText()).isEmpty()){
            this.jtxtUsuario.setText("Ingrese usuario");
            this.jtxtUsuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jtxtClaveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JButton jbtnIngresar;
    public javax.swing.JButton jbtnSalir;
    public javax.swing.JTextField jtxtClave;
    public javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
