/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_Recuperacion;
import Modelo.ClsConsultaUsuario;
import Modelo.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author monta
 */
public class frmRecuperacion extends javax.swing.JFrame {

    /**
     * Creates new form frmRecuperacion
     */
    public frmRecuperacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtrecus = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblresto = new javax.swing.JLabel();
        btnenviar1 = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 75, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_data_backup_30px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 77, 56));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recuperación de Clave");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        txtrecus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtrecus.setForeground(new java.awt.Color(204, 204, 204));
        txtrecus.setText("Ingrese usuario para recuperar la clave");
        txtrecus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtrecusMousePressed(evt);
            }
        });
        getContentPane().add(txtrecus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 637, 33));

        btnenviar.setBackground(new java.awt.Color(0, 75, 159));
        btnenviar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnenviar.setText("Enviar");
        btnenviar.setBorder(null);
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 120, 49));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Su clave se envió al siguiente correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblresto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(lblresto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 450, 20));

        btnenviar1.setBackground(new java.awt.Color(0, 75, 159));
        btnenviar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnenviar1.setForeground(new java.awt.Color(255, 255, 255));
        btnenviar1.setText("Salir");
        btnenviar1.setBorder(null);
        btnenviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnenviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 101, 40));

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar.gif"))); // NOI18N
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 40, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrecusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrecusMousePressed
        if(this.txtrecus.getText().equals("Ingrese usuario para recuperar la clave")){
            this.txtrecus.setText("");
            this.txtrecus.setForeground(Color.black);
        }

       
    }//GEN-LAST:event_txtrecusMousePressed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        if("Ingrese usuario para recuperar la clave".equals(txtrecus.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar datos");
        }
        else if("".equals(txtrecus.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar datos");
        }
        else{
            Usuario usuario = new Usuario();
            ClsConsultaUsuario consulta_usuario = new ClsConsultaUsuario();
            Ctrl_Recuperacion ctrl = new Ctrl_Recuperacion(usuario,consulta_usuario);
            ctrl.Iniciar();
            if(ctrl.Enviar(txtrecus.getText())){
                lblresto.setText(ctrl.destinatario);
            }
        }
        
            
            
        
    }//GEN-LAST:event_btnenviarActionPerformed

    private void btnenviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviar1ActionPerformed
       frmLogin login = new frmLogin();
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnenviar1ActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
      this.txtrecus.setText("Ingrese usuario para recuperar la clave");
      this.txtrecus.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_btnactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecuperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btnenviar;
    public javax.swing.JButton btnenviar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblresto;
    public javax.swing.JTextField txtrecus;
    // End of variables declaration//GEN-END:variables
}
