/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.Ctrl_Usuario;
import Modelo.ClsConsultaUsuario;
import Modelo.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author monta
 */
public class frmuser extends javax.swing.JPanel {

    /**
     * Creates new form frmuser
     */
    public frmuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterias = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnsugerir = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblImagen = new javax.swing.JLabel();
        btnregistrate1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese usuario");
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));

        txtContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseña.setText("Ingrese contraseña");
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaMousePressed(evt);
            }
        });
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 210, 30));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 40, -1));

        tbMaterias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Correo", "Usuario", "Contraseña", "Imagen"
            }
        ));
        tbMaterias.setGridColor(new java.awt.Color(255, 255, 255));
        tbMaterias.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbMaterias.setRowHeight(25);
        tbMaterias.setSelectionBackground(new java.awt.Color(0, 112, 224));
        jScrollPane1.setViewportView(tbMaterias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 430, 240));

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar Por nombre de Usuario");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 30));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-broom-with-a-lot-of-dust-40.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 40, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-40.png"))); // NOI18N
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 30, 40));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-40.png"))); // NOI18N
        btnUpdate.setBorder(null);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar.gif"))); // NOI18N
        add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 40, 40));

        btnIngresar.setBackground(new java.awt.Color(0, 112, 224));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-guardar-94.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_search_30px.png"))); // NOI18N
        add(btnBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 50, 30));

        jLabel4.setBackground(new java.awt.Color(0, 75, 159));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-users-48.png"))); // NOI18N
        jLabel4.setText("CREAR USUARIOS");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 100));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1180, 24));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 10, 500));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Datos Guardados");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 150, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Correo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtcorreo.setText("Ingrese correo");
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 210, 30));

        btnsugerir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnsugerir.setForeground(new java.awt.Color(0, 75, 159));
        btnsugerir.setText("Clic aquí para Sugerir Clave Segura");
        btnsugerir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsugerirMouseClicked(evt);
            }
        });
        add(btnsugerir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 75, 159));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 190, 10));

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_user_100px.png"))); // NOI18N
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 75, 159)));
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 130));

        btnregistrate1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnregistrate1.setForeground(new java.awt.Color(0, 75, 159));
        btnregistrate1.setText("Seleccionar Imagen");
        btnregistrate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrate1MouseClicked(evt);
            }
        });
        add(btnregistrate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 75, 159));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(this.txtUsuario.getText().equals("Ingrese usuario")){
            this.txtUsuario.setText("");
            this.txtUsuario.setForeground(Color.black);
        }

        if(String.valueOf(this.txtBuscar.getText()).isEmpty()){
            this.txtBuscar.setText("Buscar Por nombre de Usuario");
            this.txtBuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtContraseña.getText()).isEmpty()){
            this.txtContraseña.setText("Ingrese contraseña");
            this.txtContraseña.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtcorreo.getText()).isEmpty()){
            this.txtcorreo.setText("Ingrese correo");
            this.txtcorreo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
         if(this.txtBuscar.getText().equals("Buscar Por nombre de Usuario")){
            this.txtBuscar.setText("");
            this.txtBuscar.setForeground(Color.black);
        }
        if(String.valueOf(this.txtUsuario.getText()).isEmpty()){
            this.txtUsuario.setText("Ingrese usuario");
            this.txtUsuario.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtContraseña.getText()).isEmpty()){
            this.txtContraseña.setText("Ingrese contraseña");
            this.txtContraseña.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtcorreo.getText()).isEmpty()){
            this.txtcorreo.setText("Ingrese correo");
            this.txtcorreo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMousePressed
        if(this.txtContraseña.getText().equals("Ingrese contraseña")){
            this.txtContraseña.setText("");
            this.txtContraseña.setForeground(Color.black);
        }

        if(String.valueOf(this.txtBuscar.getText()).isEmpty()){
            this.txtBuscar.setText("Buscar Por nombre de Usuario");
            this.txtBuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtUsuario.getText()).isEmpty()){
            this.txtUsuario.setText("Ingrese usuario");
            this.txtUsuario.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtcorreo.getText()).isEmpty()){
            this.txtcorreo.setText("Ingrese correo");
            this.txtcorreo.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtContraseñaMousePressed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        if(this.txtcorreo.getText().equals("Ingrese correo")){
            this.txtcorreo.setText("");
            this.txtcorreo.setForeground(Color.black);
        }

        if(String.valueOf(this.txtBuscar.getText()).isEmpty()){
            this.txtBuscar.setText("Buscar Por nombre de Usuario");
            this.txtBuscar.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtUsuario.getText()).isEmpty()){
            this.txtUsuario.setText("Ingrese usuario");
            this.txtUsuario.setForeground(new Color(204,204,204));
        }
        if(String.valueOf(this.txtContraseña.getText()).isEmpty()){
            this.txtContraseña.setText("Ingrese contraseña");
            this.txtContraseña.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void btnsugerirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsugerirMouseClicked
        Usuario usuario = new Usuario();
        ClsConsultaUsuario consultaUsuario = new ClsConsultaUsuario();
        frmuser registrarse = new frmuser();
        Ctrl_Usuario ctrl = new Ctrl_Usuario(usuario, consultaUsuario, registrarse);
        String sugerenciaClave = ctrl.generarClaveSugerida();
        this.txtContraseña.setForeground(Color.black);
        txtContraseña.setText(sugerenciaClave);

    }//GEN-LAST:event_btnsugerirMouseClicked

    private void btnregistrate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrate1MouseClicked
        Usuario usuario = new Usuario();
        ClsConsultaUsuario consultaUsuario = new ClsConsultaUsuario();
        frmuser registrarse = new frmuser();
        Ctrl_Usuario ctrl = new Ctrl_Usuario(usuario, consultaUsuario, registrarse);
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ctrl.Ruta = fileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(ctrl.Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), 0));
            lblImagen.setIcon(mIcono);
        }
    }//GEN-LAST:event_btnregistrate1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBusca;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JButton btnactualizar;
    private javax.swing.JLabel btnregistrate1;
    public javax.swing.JLabel btnsugerir;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel lblImagen;
    public javax.swing.JTable tbMaterias;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
